# Generated by Django 6.0.4 on 2026-04-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_category_slug_alter_course_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instructor',
            new_name='instructor_name',
        ),
    ]
