# Generated by Django 6.0.4 on 2026-04-21 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_instructor_course_instructor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instructor_name',
            new_name='instructor',
        ),
    ]
