# Generated by Django 6.0.4 on 2026-04-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_review_company_review_review_type_and_more'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wishlist_courses',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='courses.course'),
        ),
    ]
